const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '../public');
const data = JSON.parse(fs.readFileSync(path.join(root, 'content.json')));
const e = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes = {home:'/',demos:'/demos/',portfolio:'/portfolio/',learning:'/learning/',about:'/about/',admin:'/admin/'};
const names = {home:'Home',demos:'Demos',portfolio:'Portfolio',learning:'Learning',about:'About Us',admin:'Content editor'};
const link = (url,text,cls='button') => `<a class="${cls}" href="${e(url)}">${e(text)}</a>`;
const card = (item,i,type) => `<article class="project-card"><div class="card-top"><span class="index">${String(i+1).padStart(2,'0')}</span><span class="eyebrow">${e(item.category)}</span></div><h3>${e(item.title)}</h3><p>${e(item.description)}</p><div class="card-bottom">${item.url ? link(item.url,type==='projects'?'View on GitHub ↗':type==='learning'?'Explore learning ↗':'Open demo ↗','text-link') : '<span class="status">'+e(item.status)+'</span>'}</div></article>`;
const list = (items,type) => items.filter(x=>x.status!=='Draft').map((x,i)=>card(x,i,type)).join('');
function content(page){
if(page==='home')return `<section class="hero"><div class="wrap hero-grid"><div><p class="eyebrow light">AI ethics · Bias prevention · Privacy protection</p><h1 data-site="headline">${e(data.site.headline)}</h1><p class="hero-copy" data-site="intro">${e(data.site.intro)}</p><div class="actions">${link('/portfolio/','Explore the work')}${link('/about/','Meet Binary Rights','button secondary')}</div></div><div class="brand-panel"><img src="/assets/shield.svg" alt="Binary Rights shield: justice, connected systems, and privacy" width="350" height="390"><p>Fairness. Accountability. Trust.</p></div></div></section><section class="section wrap"><div class="section-heading"><div><p class="eyebrow">From principle to practice</p><h2>Ideas become useful<br>when we put them to work.</h2></div><p>Explore the projects, experiments, and learning behind Binary Rights.</p></div><div class="path-grid"><a class="path-card" href="/demos/"><span class="index">01 / EXPLORE</span><h3>Working demos</h3><p>Experience ideas through interactive web applications.</p><span class="text-link">Explore demos →</span></a><a class="path-card" href="/portfolio/"><span class="index">02 / EXAMINE</span><h3>The portfolio</h3><p>Explore governance curricula and the source behind the work.</p><span class="text-link">View projects →</span></a><a class="path-card" href="/learning/"><span class="index">03 / LEARN</span><h3>Learning with purpose</h3><p>Build the knowledge to question, assess, and govern AI.</p><span class="text-link">Discover learning →</span></a></div></section><section class="section tinted"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">Selected work</p><h2>Governance you can practice.</h2></div>${link('/portfolio/','View the full portfolio →','text-link')}</div><div class="project-grid" data-collection="featured">${list(data.projects.slice(0,2),'projects')}</div></div></section>`;
if(page==='portfolio')return `<section class="page-head wrap"><p class="eyebrow">The work / Portfolio</p><h1>Principles, put into practice.</h1><p>Curricula and resources built to connect responsible AI with the work of governance.</p></section><section class="wrap section compact"><div class="project-grid" data-collection="projects">${list(data.projects,'projects')}</div></section>`;
if(page==='demos')return `<section class="page-head wrap"><p class="eyebrow">The work / Demos</p><h1>Explore. Interact. Question.</h1><p>A space for live web applications and practical experiments.</p></section><section class="wrap section compact"><div class="project-grid" data-collection="demos"><div class="empty-state"><span class="eyebrow">In preparation</span><h2>The next idea is taking shape.</h2><p>Live demos will appear here as they are published. In the meantime, explore the work behind Binary Rights.</p>${link('/portfolio/','Explore the portfolio','button navy')}</div></div></section>`;
if(page==='learning')return `<section class="page-head wrap"><p class="eyebrow">Learning / Beyond the interface</p><h1>Understand the machine.<br>Shape what comes next.</h1><p>Learning experiences for the people who build, evaluate, and govern technology.</p></section><section class="wrap section compact"><div class="project-grid learning-grid" data-collection="learning">${list(data.learning,'learning')}</div></section>`;
if(page==='about')return `<section class="page-head wrap"><p class="eyebrow">About us / Binary Rights</p><h1 data-site="aboutTitle">${e(data.site.aboutTitle)}</h1><p data-site="aboutBody">${e(data.site.aboutBody)}</p></section><section class="section tinted"><div class="wrap about-grid"><div><p class="eyebrow">Our focus</p><h2>People at the center.<br>Accountability by design.</h2></div><div class="principles"><article><span>01</span><div><h3>AI ethics</h3><p>Ask who a system serves, who it affects, and who is accountable for its decisions.</p></div></article><article><span>02</span><div><h3>Bias prevention</h3><p>Examine assumptions and outcomes, and make fairness part of the work.</p></div></article><article><span>03</span><div><h3>Privacy protection</h3><p>Treat personal information and the people behind it with care.</p></div></article></div></div></section><section class="section wrap founder"><p class="eyebrow">The practitioner behind the work</p><h2 data-site="founderTitle">${e(data.site.founderTitle)}</h2><p data-site="founderBody">${e(data.site.founderBody)}</p>${link(data.site.github,'Explore Jason’s work on GitHub ↗','text-link')}</section>`;
return `<section class="page-head wrap"><p class="eyebrow">Binary Rights / Administration</p><h1>Content editor</h1><p>Manage page text, portfolio projects, demos, and learning links.</p></section><section class="wrap section compact" id="editor"><p role="status">Checking your access…</p></section>`;
}
for(const page of Object.keys(routes)){
const nav=['demos','portfolio','learning','about'].map(k=>`<a href="${routes[k]}" ${page===k?'aria-current="page"':''}>${names[k]}</a>`).join('');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page==='home'?'Binary Rights | Responsible AI, practical governance':names[page]+' | Binary Rights'}</title><meta name="description" content="Binary Rights: AI ethics, bias prevention, and privacy protection through practical projects and learning.">${page==='admin'?'<meta name="robots" content="noindex,nofollow">':''}<link rel="canonical" href="https://www.stopaibias.com${routes[page]}"><link rel="icon" href="/assets/favicon.ico"><link rel="stylesheet" href="/styles.css"><script src="/${page==='admin'?'admin':'app'}.js" defer></script></head><body data-page="${page}"><a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap header-inner"><a href="/" class="brand" aria-label="Binary Rights home"><img src="/assets/shield.svg" alt="" width="43" height="49"><span>Binary Rights<small>Responsible AI. Human impact.</small></span></a><nav aria-label="Main navigation">${nav}</nav></div></header><main id="main">${content(page)}</main><footer><div class="wrap footer-top"><div><a class="footer-brand" href="/">Binary Rights</a><p>AI ethics. Bias prevention. Privacy protection.</p></div><a href="${e(data.site.github)}" data-github>GitHub ↗</a></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Binary Rights</span><span>stopaibias.com</span><a href="/admin/">${page==='admin'?'Editor':'Editor sign in'}</a></div></footer></body></html>`;
const dir=page==='home'?root:path.join(root,page);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);
}
fs.copyFileSync(path.join(root,'content.json'),path.join(__dirname,'../api/seed.json'));
console.log('Built six pages and synchronized fallback content.');
